Add-Type -AssemblyName System.Drawing

# Create 512x512 icon
$bitmap = New-Object System.Drawing.Bitmap(512, 512)
$graphics = [System.Drawing.Graphics]::FromImage($bitmap)
$graphics.Clear([System.Drawing.Color]::Black)
$font = New-Object System.Drawing.Font('Arial', 300, [System.Drawing.FontStyle]::Bold)
$brush = New-Object System.Drawing.SolidBrush([System.Drawing.Color]::White)
$graphics.DrawString('M', $font, $brush, 100, 100)
$bitmap.Save('temp_icon_512.png', [System.Drawing.Imaging.ImageFormat]::Png)
$graphics.Dispose()
$bitmap.Dispose()

# Create 192x192 icon
$bitmap = New-Object System.Drawing.Bitmap(192, 192)
$graphics = [System.Drawing.Graphics]::FromImage($bitmap)
$graphics.Clear([System.Drawing.Color]::Black)
$font = New-Object System.Drawing.Font('Arial', 120, [System.Drawing.FontStyle]::Bold)
$brush = New-Object System.Drawing.SolidBrush([System.Drawing.Color]::White)
$graphics.DrawString('M', $font, $brush, 40, 40)
$bitmap.Save('temp_icon_192.png', [System.Drawing.Imaging.ImageFormat]::Png)
$graphics.Dispose()
$bitmap.Dispose()

# Create 144x144 icon (for mdpi)
$bitmap = New-Object System.Drawing.Bitmap(144, 144)
$graphics = [System.Drawing.Graphics]::FromImage($bitmap)
$graphics.Clear([System.Drawing.Color]::Black)
$font = New-Object System.Drawing.Font('Arial', 90, [System.Drawing.FontStyle]::Bold)
$brush = New-Object System.Drawing.SolidBrush([System.Drawing.Color]::White)
$graphics.DrawString('M', $font, $brush, 30, 30)
$bitmap.Save('temp_icon_144.png', [System.Drawing.Imaging.ImageFormat]::Png)
$graphics.Dispose()
$bitmap.Dispose()

# Create 96x96 icon (for ldpi)
$bitmap = New-Object System.Drawing.Bitmap(96, 96)
$graphics = [System.Drawing.Graphics]::FromImage($bitmap)
$graphics.Clear([System.Drawing.Color]::Black)
$font = New-Object System.Drawing.Font('Arial', 60, [System.Drawing.FontStyle]::Bold)
$brush = New-Object System.Drawing.SolidBrush([System.Drawing.Color]::White)
$graphics.DrawString('M', $font, $brush, 20, 20)
$bitmap.Save('temp_icon_96.png', [System.Drawing.Imaging.ImageFormat]::Png)
$graphics.Dispose()
$bitmap.Dispose()

# Create 72x72 icon (for mdpi)
$bitmap = New-Object System.Drawing.Bitmap(72, 72)
$graphics = [System.Drawing.Graphics]::FromImage($bitmap)
$graphics.Clear([System.Drawing.Color]::Black)
$font = New-Object System.Drawing.Font('Arial', 45, [System.Drawing.FontStyle]::Bold)
$brush = New-Object System.Drawing.SolidBrush([System.Drawing.Color]::White)
$graphics.DrawString('M', $font, $brush, 15, 15)
$bitmap.Save('temp_icon_72.png', [System.Drawing.Imaging.ImageFormat]::Png)
$graphics.Dispose()
$bitmap.Dispose()

# Create 48x48 icon (for mdpi)
$bitmap = New-Object System.Drawing.Bitmap(48, 48)
$graphics = [System.Drawing.Graphics]::FromImage($bitmap)
$graphics.Clear([System.Drawing.Color]::Black)
$font = New-Object System.Drawing.Font('Arial', 30, [System.Drawing.FontStyle]::Bold)
$brush = New-Object System.Drawing.SolidBrush([System.Drawing.Color]::White)
$graphics.DrawString('M', $font, $brush, 10, 10)
$bitmap.Save('temp_icon_48.png', [System.Drawing.Imaging.ImageFormat]::Png)
$graphics.Dispose()
$bitmap.Dispose()

Write-Host "Icons created successfully!"
